### ISSUE TITLE
PEM routines:PEM_read_bio:no start line     at Sign.sign (internal/crypto/sig.js:85:26)

### ISSUE THREAD

**Issue by theronic** [scottrhoyt/apple-music-jwt#3]
I ran `npm install apple-music-jwt` and put the following in an index.js file (keys redacted):

```
var keyID = 'music.com.mydomain.myproject';
var teamID = 'VWxxxxxxxx';
var secret = 'MIGT... '; // from AuthKey_<some value>.p8 file
```

When I run `node index.js`, I get the the following error:

```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (internal/crypto/sig.js:85:26)
    at sign (/Users/petrus/Projects/apple-music-jwt/node_modules/jwa/index.js:55:45)
    at Object.sign (/Users/petrus/Projects/apple-music-jwt/node_modules/jwa/index.js:75:27)
    at Object.jwsSign [as sign] (/Users/petrus/Projects/apple-music-jwt/node_modules/jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (/Users/petrus/Projects/apple-music-jwt/node_modules/jsonwebtoken/sign.js:189:16)
    at Object.module.exports.generate (/Users/petrus/Projects/apple-music-jwt/node_modules/apple-music-jwt/src/index.js:24:14)
    at Object.<anonymous> (/Users/petrus/Projects/apple-music-jwt/index.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
```

What am I doing wrong? This JWT stuff is so hard.

**Comment by NetOpWibby** [comment]
You gotta read the p8 file (fs.readFileSync).
